# Generated by Django 5.2.1 on 2025-07-15 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_athlete',
        ),
        migrations.AddField(
            model_name='customuser',
            name='managed_users',
            field=models.ManyToManyField(blank=True, related_name='managed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('athlete', 'Athlete')], default='athlete', max_length=20),
        ),
    ]
