# Generated by Django 5.2.1 on 2025-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpurchase',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportpurchase',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='period_usage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
