# Generated by Django 5.2.1 on 2025-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletereport',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
