# Generated by Django 5.2.1 on 2025-07-14 09:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_athletereport_file_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='athletereport',
            unique_together={('user', 'file_hash')},
        ),
    ]
