# Generated by Django 5.2.1 on 2025-07-14 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_athletereport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
