# Generated by Django 5.2.1 on 2025-07-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_athletereport_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletereport',
            name='s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
