# Generated by Django 5.2.1 on 2025-09-18 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_videourl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videourl',
            unique_together={('user', 'url')},
        ),
    ]
