# Generated by Django 5.2.1 on 2026-03-05 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_videourl_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_sessions', to='reports.athletereport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AnnotationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField()),
                ('timestamp_seconds', models.FloatField()),
                ('player', models.CharField(choices=[('me', 'Me'), ('opponent', 'Opponent'), ('ai_coach', 'AI Coach')], max_length=20)),
                ('event_type', models.CharField(choices=[('position', 'Position'), ('transition', 'Transition'), ('submission', 'Submission'), ('note', 'Note')], max_length=20)),
                ('move_name', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reports.annotationsession')),
            ],
            options={
                'ordering': ('match_number', 'timestamp_seconds', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AnnotationMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField()),
                ('result', models.CharField(choices=[('Win', 'Win'), ('Lost', 'Lost'), ('Draw', 'Draw')], default='Win', max_length=20)),
                ('match_type', models.CharField(default='No-GI Points', max_length=100)),
                ('referee_decision', models.BooleanField(default=False)),
                ('disqualified', models.BooleanField(default=False)),
                ('opponent', models.CharField(default='Unknown Opponent', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='reports.annotationsession')),
            ],
            options={
                'ordering': ('match_number',),
                'unique_together': {('session', 'match_number')},
            },
        ),
    ]
