# Generated by Django 5.2.1 on 2026-03-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_annotationsession_annotationevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationevent',
            name='player',
            field=models.CharField(choices=[('me', 'Me'), ('opponent', 'Opponent')], max_length=20),
        ),
    ]
