# Generated by Django 5.2.1 on 2026-03-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_annotationevent_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='videourl',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videourl',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videourl',
            name='file_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videourl',
            name='s3_key',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
