# Generated by Django 5.2.1 on 2026-03-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_videourl_content_type_videourl_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videourl',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
