# Generated by Django 5.2.1 on 2026-03-09 00:29

import django.db.models.deletion
from django.db import migrations, models


def backfill_session_video_fk(apps, schema_editor):
    AnnotationSession = apps.get_model("reports", "AnnotationSession")
    VideoUrl = apps.get_model("reports", "VideoUrl")

    sessions = (
        AnnotationSession.objects
        .filter(video_id__isnull=True)
        .exclude(video_url__isnull=True)
        .exclude(video_url="")
        .only("id", "user_id", "video_url")
    )
    for session in sessions.iterator():
        video = (
            VideoUrl.objects
            .filter(user_id=session.user_id, url=session.video_url)
            .order_by("-id")
            .first()
        )
        if not video:
            continue
        session.video_id = video.id
        session.save(update_fields=["video"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_videourl_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationsession',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_sessions', to='reports.videourl'),
        ),
        migrations.RunPython(backfill_session_video_fk, noop_reverse),
    ]
