# Generated by Django 5.2.1 on 2026-03-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_annotationsession_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationevent',
            name='end_time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotationevent',
            name='start_time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
